version: '2'
services:
  tomcat:
    image: munhunger/tomcat
    build: ./tomcat
    container_name: "tomcat"
    ports:
      - "80:8080"
  jenkins:
    image: munhunger/jenkins
    build: ./jenkins
    container_name: "jenkins"
    ports:
      - "81:8080"
  