version: '3'
services:
  mongo:
    image: "mongo:3"
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: LNrGftcZBYgnXd41roa53j3CBF9jBRse
      GRAYLOG_ROOT_PASSWORD_SHA2: e569dfd7f8e981aefee513b73c9c2d2955dd640f1ee91155e48c006192383ce4
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:8000/api
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    ports:
      - "8000:9000"