version: '2'
services:
  minio-client:
    build: ./minio/client
    image: munhunger/minio-client
    container_name: "minio-client"

  tomcat:
    build: ./tomcat
    image: munhunger/tomcat
    container_name: "tomcat"
    depends_on:
      - minio-client
  
  jenkins:
    build: ./jenkins
    image: munhunger/jenkins
    container_name: "jenkins"
    depends_on:
      - tomcat
    ports:
      - "81:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.jenkins/workspace:/root/.jenkins/workspace
      - /var/lib/jenkins:/var/lib/jenkins
      - /var/lib/docker:/var/lib/docker